name: NCCL Sharp plugin CI

on:
  workflow_dispatch: 
    inputs:
      mainhost:
        description: 'Choose one of hosts to run:'
        required: true
        type: choice
        default: 'host01'
        options:
          - host01
          - host02
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:

    runs-on: [self-hosted, linux , x64]

    steps:
    - name: Deployment
      run: /start deploy
    - name: Building NCCL sharp plugin
      run: /start build      
    - name: Configuring and checking sharp
      run: /start sharp
    - name: Running tests of NCCL sharp plugin
      run: /start test
    - name: Cleaning
      run: /start clean
